import time
import pydirectinput
import pyautogui

successfulExtractionImage = 'botImages/successfulExtraction.png'


def mineOre():
    while pyautogui.locateOnScreen(successfulExtractionImage, confidence=.7, grayscale=True) != None:
        time.sleep(.25)
    while pyautogui.locateOnScreen(successfulExtractionImage, confidence=.7, grayscale=True) == None:
        pydirectinput.press('q')
        time.sleep(.25)

def goFromTheFirstOreToTheSecond():
    pydirectinput.keyDown('a')
    time.sleep(1.2)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(2)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(.5)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(2)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(.1)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(.3)
    pydirectinput.keyUp('w')

def goFromTheSecondOreToTheThird():
    pydirectinput.keyDown('s')
    time.sleep(.7)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(4.1)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(1)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('a')
    time.sleep(.8)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(.8)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(.2)
    pydirectinput.keyUp('d')
    
def goFromTheThirdOreToTheFirst():
    pydirectinput.keyDown('a')
    time.sleep(.1)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(.8)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(.8)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    time.sleep(1)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(4.3)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.5)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(.4)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.9)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(1.3)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(.1)
    pydirectinput.keyUp('w')

def goFromtheThirdOreToTheFourth():
    pydirectinput.keyDown('a')
    time.sleep(.1)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('w')
    time.sleep(1.7)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(.5)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(.7)
    pydirectinput.keyUp('w')
    pydirectinput.keyDown('d')
    time.sleep(.1)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(.2)
    pydirectinput.keyUp('w')
    
def goFromTheFourthOreToTheFifth():
    pydirectinput.keyDown('d')
    time.sleep(1)
    pydirectinput.keyUp('d')

def goFromTheFifthOreToTheSixth():
    pydirectinput.keyDown('s')
    time.sleep(.2)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(.1)
    pydirectinput.keyUp('d')

def goFromTheSixthOreToTheFirst():
    pydirectinput.keyDown('a')
    time.sleep(1.5)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(.6)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(.4)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.7)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('s')
    time.sleep(.8)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(.8)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('s')
    time.sleep(1.1)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(4.3)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.5)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('a')
    time.sleep(.4)
    pydirectinput.keyUp('a')
    pydirectinput.keyDown('s')
    time.sleep(1.8)
    pydirectinput.keyUp('s')
    pydirectinput.keyDown('d')
    time.sleep(1.3)
    pydirectinput.keyUp('d')
    pydirectinput.keyDown('w')
    time.sleep(.1)
    pydirectinput.keyUp('w')
    
time.sleep(.5)

# Start at the southernmost mining site
i = 0
while True:
    mineOre()
    goFromTheFirstOreToTheSecond()
    mineOre()
    goFromTheSecondOreToTheThird()
    mineOre()
    if i == 0:
        i = 1
        goFromtheThirdOreToTheFourth()
        mineOre()
        goFromTheFourthOreToTheFifth()
        mineOre()
        goFromTheFifthOreToTheSixth()
        mineOre()
        goFromTheSixthOreToTheFirst()
    else:
        i = 0
        goFromTheThirdOreToTheFirst()
# Return to the first ore
